EjemploMVC/Models/ErrorViewModel.cs
using System;

namespace EjemploMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EjemploMVC/Models/InicioBD.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;

namespace EjemploMVC.Models
{
    public class InicioBD
    {
        public static void Inicializar(IServiceProvider serviceProvider)
        {
            using (var context = new EjemploMVCContext(serviceProvider.GetRequiredService<DbContextOptions<EjemploMVCContext>>()))
            {
                if (context.Videos.Any())
                {
                    return;
                }
                context.Videos.AddRange(
                    new Videos
                    { Titulo = "Arma Letal",
                      FechaEstreno = DateTime.Parse("01/01/92"),
                      Genero = "Acción",
                       Precio = 10},
                    new Videos
                    { Titulo = "Lo que el viento se llevó",
                      FechaEstreno = DateTime.Parse("01/01/40"),
                      Genero = "Aventuras",
                       Precio = 10},
                    new Videos
                    { Titulo = "la guerra de las galaxias",
                      FechaEstreno = DateTime.Parse("01/01/78"),
                      Genero = "Aventuras",
                      Precio = 11},
                    new Videos
                    {
                     Titulo = "Cazafantasmas",
                     FechaEstreno = DateTime.Parse("01/01/85"),
                     Genero = "Aventuras",
                     Precio = 11
                      }
                    );
                context.SaveChanges();

            }   
        }
        

    }
}

EjemploMVC/Models/Videos.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EjemploMVC.Models
{
    public class Videos
    {
        public int ID { get; set; }
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        [Display(Name = "Fecha de estreno")]
        [DisplayFormat(DataFormatString = "{0:yyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaEstreno { get; set; }
        [Display(Name = "Género")]
        public string Genero { get; set; }
        public decimal Precio { get; set; }

    }
}

EjemploMVC/Models/VistaGenero.cs
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EjemploMVC.Models
{
    public class VistaGenero
    {
        public List<Videos> L_Videos;
        public SelectList Generos;
        public string generoVideo { get; set; }
    }
}

EjemploMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EjemploMVC.Models;

namespace EjemploMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EjemploMVC/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EjemploMVC.Models;

namespace EjemploMVC.Controllers
{
    public class VideosController : Controller
    {
        private readonly EjemploMVCContext _context;

        public VideosController(EjemploMVCContext context)
        {
            _context = context;
        }

        // GET: Videos
        public async Task<IActionResult> Index(string vGenero, string vBusqueda)
        {
            IQueryable<string> busquedaGenero = from m in _context.Videos
                                                orderby m.Genero
                                                select m.Genero;

            var Videos = from m in _context.Videos select m;

            if (!String.IsNullOrEmpty(vBusqueda))
                { Videos = Videos.Where(s => s.Titulo.Contains(vBusqueda));
                }
            if (!String.IsNullOrEmpty(vGenero))
            {
                Videos = Videos.Where(x => x.Genero == vGenero);
            }

            var VistaGeneroMV = new VistaGenero();
            VistaGeneroMV.Generos = new SelectList(await busquedaGenero.Distinct().ToListAsync());
            VistaGeneroMV.L_Videos = await Videos.ToListAsync();

            return View(VistaGeneroMV);
        }

        // GET: Videos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videos = await _context.Videos
                .SingleOrDefaultAsync(m => m.ID == id);
            if (videos == null)
            {
                return NotFound();
            }

            return View(videos);
        }

        // GET: Videos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Videos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Titulo,FechaEstreno,Genero,Precio")] Videos videos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(videos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(videos);
        }

        // GET: Videos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videos = await _context.Videos.SingleOrDefaultAsync(m => m.ID == id);
            if (videos == null)
            {
                return NotFound();
            }
            return View(videos);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titulo,FechaEstreno,Genero,Precio")] Videos videos)
        {
            if (id != videos.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(videos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideosExists(videos.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(videos);
        }

        // GET: Videos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videos = await _context.Videos
                .SingleOrDefaultAsync(m => m.ID == id);
            if (videos == null)
            {
                return NotFound();
            }

            return View(videos);
        }

        // POST: Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var videos = await _context.Videos.SingleOrDefaultAsync(m => m.ID == id);
            _context.Videos.Remove(videos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideosExists(int id)
        {
            return _context.Videos.Any(e => e.ID == id);
        }
    }
}

EjemploMVC/Views/Hola/Bienvenidos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Bienvenidos";

}

<h2>Bienvenidos </h2>

<ul>
    @for (int i =0; i < (int)ViewData["Veces"]; i++)
    {
        <li>@ViewData["Mensaje"]</li>

    }

</ul>

EjemploMVC/Views/Hola/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Lista de Videos";
    }

<h2>Lista de Videos</h2>

<p>Bienvenidos a nuestro nuevo template :-)</p>   

EjemploMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EjemploMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EjemploMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

EjemploMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Videos APP</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Videos" asp-action="Index" class="navbar-brand">Videos APP</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Acerca de</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contacto</a></li>
                    <li><a asp-area="" asp-controller="Hola" asp-action="Index">Hola</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - EjemploMVC</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EjemploMVC/Views/Videos/Create.cshtml
@model EjemploMVC.Models.Videos

@{
    ViewData["Title"] = "Create";
}

<h2>Crear</h2>

<h4>Videos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label">T&iacute;tulo</label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEstreno" class="control-label">Fecha de Estreno</label>
                <input asp-for="FechaEstreno" class="form-control" />
                <span asp-validation-for="FechaEstreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label">G&eacute;nero</label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label">Precio</label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EjemploMVC/Views/Videos/Delete.cshtml
@model EjemploMVC.Models.Videos

@{
    ViewData["Title"] = "Delete";
}

<h2>Borrar</h2>

<h3>&iquest;Esta seguro de borrar?</h3>
<div>
    <h4>Videos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Borrar" class="btn btn-default" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

EjemploMVC/Views/Videos/Details.cshtml
@model EjemploMVC.Models.Videos

@{
    ViewData["Title"] = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Videos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaEstreno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaEstreno)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

EjemploMVC/Views/Videos/Edit.cshtml
@model EjemploMVC.Models.Videos

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar</h2>

<h4>Videos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label">T&iacute;tulo</label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaEstreno" class="control-label">Fecha de Estreno</label>
                <input asp-for="FechaEstreno" class="form-control" />
                <span asp-validation-for="FechaEstreno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label">G&eacute;nero</label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EjemploMVC/Views/Videos/Index.cshtml
@model EjemploMVC.Models.VistaGenero

@{
    ViewData["Title"] = "Index";
}

<h2>Listado</h2>

<form asp-controller="Videos" asp-action="Index" method="get">
    <p>
        <select name="vGenero" asp-for="generoVideo" asp-items="Model.Generos">
        <option value ="">Todos</option>
        </select>
    </p>
    <p style="text-emphasis:filled">
        T&iacute;tulo= <input type="text" name="vBusqueda" >
        <input type="submit" value="Filter"/>
    </p>
</form>

<p>
    <a asp-action="Create">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.L_Videos[0].Titulo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.L_Videos[0].FechaEstreno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.L_Videos[0].Genero)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.L_Videos[0].Precio)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.L_Videos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEstreno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalle</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>